#!/usr/bin/env python
# -*- coding: utf-8 -*-

def Triangle(limit):
	ret = set()
	for i in range(1, limit+1):
		ret.add(int(i*(i+1)/2))

	return ret

def Pentagonal(limit):
	ret = set()
	for i in range(1, limit+1):
		ret.add(int(i*(3*i-1)/2))

	return ret

def Hexagonal(limit):
	ret = set()
	for i in range(1, limit+1):
		ret.add(int(i*(2*i-1)))

	return ret

def main():

	tri = Triangle(100000)
	pent = Pentagonal(100000)
	hexa = Hexagonal(100000)

	for number in tri:
		if (number in pent and number in hexa):
			print (number)

	return 0

if __name__ == '__main__':
	main()

